In [2]:
import numpy as np
dataset = np.loadtxt('/content/transfusion.data - Copy.csv',delimiter=',',skiprows=1)

In [3]:
print(dataset.shape)

(748, 5)


In [4]:
print(dataset[:10])

[[2.00e+00 5.00e+01 1.25e+04 9.80e+01 1.00e+00]
 [0.00e+00 1.30e+01 3.25e+03 2.80e+01 1.00e+00]
 [1.00e+00 1.60e+01 4.00e+03 3.50e+01 1.00e+00]
 [2.00e+00 2.00e+01 5.00e+03 4.50e+01 1.00e+00]
 [1.00e+00 2.40e+01 6.00e+03 7.70e+01 0.00e+00]
 [4.00e+00 4.00e+00 1.00e+03 4.00e+00 0.00e+00]
 [2.00e+00 7.00e+00 1.75e+03 1.40e+01 1.00e+00]
 [1.00e+00 1.20e+01 3.00e+03 3.50e+01 0.00e+00]
 [2.00e+00 9.00e+00 2.25e+03 2.20e+01 1.00e+00]
 [5.00e+00 4.60e+01 1.15e+04 9.80e+01 1.00e+00]]


In [5]:
np.set_printoptions(formatter={'float': '{:0.2f}'.format})

In [6]:
print(dataset[:10])

[[2.00 50.00 12500.00 98.00 1.00]
 [0.00 13.00 3250.00 28.00 1.00]
 [1.00 16.00 4000.00 35.00 1.00]
 [2.00 20.00 5000.00 45.00 1.00]
 [1.00 24.00 6000.00 77.00 0.00]
 [4.00 4.00 1000.00 4.00 0.00]
 [2.00 7.00 1750.00 14.00 1.00]
 [1.00 12.00 3000.00 35.00 0.00]
 [2.00 9.00 2250.00 22.00 1.00]
 [5.00 46.00 11500.00 98.00 1.00]]


In [7]:
x = dataset[:,:-1]

In [8]:
y = dataset[:,-1]

In [9]:
print(x.shape, y.shape)

(748, 4) (748,)


In [10]:
mean = x.mean(axis=0)
x -= mean
std = x.std(axis=0)
x /= std

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential()
model.add(Dense(8,input_dim = len(x[0, : ]),activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='sigmoid'))


In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 5         
Total params: 81
Trainable params: 81
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [15]:
model.fit(x=x,y=y,epochs=2000,verbose=1)

Epoch 1/2000
24/24 [==============================] - 1s 1ms/step - loss: 0.7236 - accuracy: 0.7620
Epoch 2/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.6831 - accuracy: 0.7620
Epoch 3/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.6526 - accuracy: 0.7620
Epoch 4/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.6230 - accuracy: 0.7620
Epoch 5/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.5957 - accuracy: 0.7620
Epoch 6/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.5731 - accuracy: 0.7620
Epoch 7/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.5534 - accuracy: 0.7620
Epoch 8/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.5402 - accuracy: 0.7620
Epoch 9/2000
24/24 [==============================] - 0s 1ms/step - loss: 0.5286 - accuracy: 0.7620
Epoch 10/2000
24/24 [==============================] - 0s 2ms/step - loss: 0.5188 - accuracy: 0.7620

In [16]:
prediction = model.predict(x)

In [17]:
print(prediction[:5])

[[0.79]
 [0.74]
 [0.71]
 [0.78]
 [0.74]]


In [18]:
print(y[:5])

[1.00 1.00 1.00 1.00 0.00]


In [19]:
from sklearn.metrics import accuracy_score,precision_score , recall_score ,f1_score

In [20]:
my_accuracy = accuracy_score(y , prediction.round())
print(my_accuracy)

0.8101604278074866


In [21]:
len(y)

748

In [22]:
y.sum()

178.0

In [23]:
178/748

0.23796791443850268

In [24]:
 precision = precision_score(y,prediction.round())
 print(precision)

0.65


In [25]:
recall = recall_score(y,prediction.round())
print(recall)

0.43820224719101125


In [26]:
from tensorflow import keras
from tensorflow import lite


In [27]:
keras_file='binary.h5'

In [28]:
tf.keras.models.save_model(model,keras_file)

In [29]:
converter = lite.TFLiteConverter.from_keras_model(model)

In [30]:
tfmodel = converter.convert()

INFO:tensorflow:Assets written to: /tmp/tmplyh5mfdt/assets


In [31]:
open("binary.tflite","wb").write(tfmodel)

2080